name: Automated Web Scraper

on:
  schedule:
    - cron: "0 * * * *"      # runs every hour
  workflow_dispatch:         # allows manual run from GitHub UI

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install selenium

      - name: Run scraper
        run: python auction-backend/scraper_bank.py
