name: Automated Web Scraper

on:
  schedule:
    - cron: "0 * * * *"    # runs every hour (you can change this)
  workflow_dispatch:       # lets you start it manually if you want

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

  
      - name: Run scraper
        run: python auction-backend/scraper_bank.py
