name: Automated Web Scraper

on:
  schedule:
    - cron: "0 * * * *"      # runs every hour
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          sudo ln -s /usr/bin/chromedriver /usr/bin/google-chrome # for some runners

      - name: Install selenium
        run: pip install selenium

      - name: Debug files
        run: ls -la auction-backend
        # You can also print the contents of states.txt for extra debug:
        # run: cat auction-backend/states.txt

      - name: Run scraper
        run: python auction-backend/scraper_bank.py
