name: Automated Web Scraper

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          [ ! -e /usr/bin/google-chrome ] && sudo ln -s /usr/bin/chromedriver /usr/bin/google-chrome || echo 'Link exists, skip symlink'

      - name: Install selenium
        run: pip install selenium

      - name: Debug files
        run: ls -la auction-backend

      - name: Run scraper
        run: python auction-backend/scraper_bank.py
